baseURL = "https://abdullah.today/"
languageCode = "en-us"
title = "Abdullah"
theme = "minimal"
disqusShortname = "akpk"
googleAnalytics = "UA-147400444-1"
enableEmoji = true
enableGitInfo = true
canonifyURLs = true

[params]
    author = "Abdullah"
    description = "A tech blog mostly related to the use of configurable software to achieve a more efficient and keyboard driven workflow"
    githubUsername = "Awan"
    accent = ""
    backgroundColor = "floralwhite"
    font = "Source Sans Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-light"
    highlightLanguages = ["go", "bash", "python", "zsh", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/Quran/"
    name = "Quran"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:abdullah@abdullah.today"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://gitlab.com/Abdullah"
    name = "gitlab"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/0x5CBC7BC7"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://t.me/AbdullahToday"
    name = "telegram"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/11274908/abdullah"
    name = "stack-overflow"
    weight = 5
