baseURL = "https://abdullah.today/"
languageCode = "en-us"
copyright = "Copyleft! All rights reversed. Internet is free and so is my content"
title = "Abdullah"
theme = "minimal"
toc = true
disqusShortname = "akpk"
googleAnalytics = "UA-147400444-1"
enableEmoji = true
enableGitInfo = true
canonifyURLs = true

[params]
    author = "Abdullah"
    description = "Four things support the world: the learning of the wise, the justice of the great, the prayers of the good, and the valor of the brave"
    githubUsername = "Awan"
    accent = ""
    backgroundColor = "floralwhite"
    font = "Source Sans Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-light"
    highlightLanguages = ["go", "bash", "python", "zsh", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 3
    staticDir = "/content/blog/"

[[menu.main]]
    url = "/Quran/"
    name = "Quran"
    weight = 4

[[menu.main]]
  url = "/Hadith/"
  name = "Hadith"
  weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:abdullah@abdullah.today"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://gitlab.com/Abdullah"
    name = "gitlab"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/0x5CBC7BC7"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://t.me/AbdullahToday"
    name = "telegram"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/11274908/abdullah"
    name = "stack-overflow"
    weight = 5


[permalinks]
  blog = "/:slug/"

